# Generated by Django 4.2.8 on 2023-12-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_remove_employee_contact_info_alter_employee_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(name="ContactInfo",),
    ]
